name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]

jobs:
  stress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: make install
             pip install "anyio<4"
             pip install "pytest==7.4.4"

      - name: Run stress test
        run: make stress-test